### ISSUE TITLE
Authorization header not present  trying to get a list of the Expertise

### ISSUE THREAD

**Issue by fe01134** [Watson-Personal-Assistant/Beta-Support#2]
Documentation doesn't provide explanation of how to access Watson Assistant APIs from the command line using API SWAGGER doc curl commands with API Key

**Steps to reproduce**
1.  Tried doing tutorial to add first skill.  Step 2: Add the skill to the Assistant  
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "name": "myHelloWorld", "url": "https://8112bdc0.ngrok.io" }' 'https://watson-personal-assistant-toolkit.mybluemix.net/v2/api/skills?api_key=mykey'

Gave error:
```
     <!DOCTYPE html>
     <html lang="en">
     <head>
     <meta charset="utf-8">
     <title>Error</title>
     </head>
     <body>
     <pre>Cannot POST /v2/api/skills</pre>
     </body>
     </html>
```

2. Gave error cannot Post.  so then tried to troubleshoot to see if the Watson Assistatnn service was accessible  by going to swagger doc to get CURL URL  for get /expertise/AllExpertise  which gives
$curl -X GET --header 'Accept: application/json' 'https://watson-personal-assistant-toolkit.mybluemix.net/v1/api/expertise/AllExpertise'

3. Open Terminal window on local development environment and enter that CURL command and it gives error using the url in the SWAGGER DOC curl command which references v1 in the actual command even though the title says v2.  (This needs to be fixed):
$ curl -X GET --header 'Accept: application/json' 'https://watson-personal-assistant-toolkit.mybluemix.net/v1/api/expertise/AllExpertise'
_Authorization header not present(expertise-boilerplate-python)_ 

4.  That same command works in the SWAGGER Test page in the browser because the header / authentication has been added.

**FIX**
We need to include directions on passing in header for API key.

This command worked and should be documented in the doc and in the SWAGGER default doc behavior:
curl -X GET --header 'Accept: application/json' 'https://watson-personal-assistant-toolkit.mybluemix.net/v1/api/expertise/AllExpertise?api_key=myAPIKey'

**Comment by erezbi** [comment]
It seems you are using an old instance. We don't have 'expertise' anymore. We don't have 'v1' anymore.

I am guessing the first error that you got was because of trying to access 'skill' endpoint on an out of date instance, that still uses 'expertise'.

Please open an internal ticket with the relevant instance details, to upgrade  this instance, or get a new one.
