### ISSUE TITLE
Access-Control-Allow-Origin header is not present on 'converse' responses

### ISSUE THREAD

**Issue by TimonLukas** [Watson-Personal-Assistant/Beta-Support#4]
See this as an example: https://watson-assistant-chat.mybluemix.net/

Enter any API key, choose under "Anfrage senden an:" "Einen bestimmten Skill", and just choose "built-in-skill-weather" or something. Then look into the console, or look at the request in the Network menu. You'll see that an error regarding the origin not being allowed will be logged.

**Comment by troyibm** [comment]
I'm unable to reproduce this problem but I have seen the ACAO header issue before when calling converse and it has boiled down to having the wrong API key but Chrome gave the ACAO error.
Reopen if you can reproduce the problem.
