### ISSUE TITLE
Broked link in the documentation

### ISSUE THREAD

**Issue by sanserg** [Watson-Personal-Assistant/Beta-Support#6]
See Core Architecture in Product Documentation page

**Comment by troyibm** [comment]
fixed now.

**Comment by sanserg** [comment]
Great!
Thanks

**Comment by sanserg** [comment]
Hi Support,
 
I am getting an error message trying to connect app demo...already installed the app on my iphone 
 
http://cs-room-simulator.mybluemix.net/
 

 
Do you know if the application is down ? Or maybe I am doing something wrong here ?
 
Thanks
 
Sandra
 
 
 
                                                                                                Sandra Sergi Santos
                        IBM IT Specialist | CSM | DAD | SPC
                        IoT - ALM DevOps - Development Tools
                        Cel:+55 11 97144-8139
                        email: ssergi@br.ibm.com
                                                                         
 
 
 
----- Original message -----From: Troy Dugger <notifications@github.com>To: Watson-Personal-Assistant/Beta-Support <Beta-Support@noreply.github.com>Cc: sanserg <ssergi@br.ibm.com>, Author <author@noreply.github.com>Subject: Re: [Watson-Personal-Assistant/Beta-Support] Broked link in the documentation (#6)Date: Tue, May 8, 2018 4:05 PM 
fixed now.
