### ISSUE TITLE
Message Connection failed ...Connection

### ISSUE THREAD

**Issue by sanserg** [Watson-Personal-Assistant/Beta-Support#7]
Hi Support,
 
I am getting an error message trying to connect app demo...already installed the app on my iphone  and set the device name
 
http://cs-room-simulator.mybluemix.net/
 
Message Connection failed ...Connection
 
Do you know if the application is down ? Or maybe I am doing something wrong here ?
 
Thanks
 
Sandra

**Comment by troyibm** [comment]
I'm able to see the UI at that URL.  the http part looks funny.  I think you should use https://cs-room-simulator.mybluemix.net

But I see the room simulation UI when I hit that URL.

**Comment by sanserg** [comment]
oh...worked now!
thanks
